import '@styles/globals.css';
import { ReactNode } from 'react';

import RecoilRootProvider from '@components/base/RecoilRootProvider';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Co-Bounty',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={'bg-coDark'}>
        <RecoilRootProvider>{children}</RecoilRootProvider>
      </body>
    </html>
  );
}
